services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped

  app:
    image: spring-boot-ducks
    ports:
      - 8080:8080
    environment:
      FIREBASE_PROJECT: my-playground-project-391323
      DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
